language: node_js
node_js:
- '4.0'
- '5.0'
- '6.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: dBnjo9a2nD89IRK7gtRCRo3HSJGmfSyLwXg14RspN1Mh86zg55UJF6F+ZbMbERFapoh7qNip/iU20Y3R6KLgSHHPIUqZ/yR4+0EoJ1przAknnSs8+disRl8LQSxc+cwKFcNYLCaIzsiPJ22REu5PeWsyUPJhnMNQEZX3UI9upFN2H5Hw4Ja9d+u7pUhsySVCg1hiFQwJhCEApLaOkU+ZO+jpuQOzJIEZ1fCvP0AiVTBA6nrd6fVnRz2Nq+wn1GBeL5CqfkTtNhrjSUIXaBWXd6jecQHB8Mee16DYKNncCPOGKZSXZ/b1Teqr03sxrXF4fyCGxO6UTBFGBA0f9kvSk81YNKi2tQpL4XUUgvtUqNIS809CgRi7iQgRtSuPf+7bNST7yC2GJQjlKfN687akCwpfWtz5hwd71HFcv5sXAVpPPzMea+SKPe3MZ3H6fBNr5+w5HNCyUIQvB51keR7pf18qRgB8Gn4cpCNRAd6AVd5m9AwsCxAmvb5EEg8kwjucOG1bBSYrPCr1bDjPAZoRdmgrkKCbedWcHEpxEA1n97fs/F1v0Lo5ZQqeJi83vQ4HPzaHzhay3FhGn44rqpUia0zhNs0J0vo6QMFM18NyzPv+fCoJtCDfFDzreXv4WYzBn5r/453Fs7bTiLq+ExD/lWoRkurtzYpKLmOsNkqZgxA=
    on:
      tags: true
      node: '5.0'
  - provider: releases
    api_key:
      secure: D32bcNwl0l5PKZNzjp0qjHuNJb7Eb3qvzuTcAwust5OsDBsuLPgADjj1spqthLJbV6ZXHfTCCG2K8pvnkF9uTlBlAKBySN2Pr4P8YLuhKAbzrkCdq0/grRhKwxlsESzcPlLNl5bQ85CLbupMIcuujEnxxwJuX+ISDm72ODjlZdEVHigaB7jsW9V0rGa3mQvucr3wLgCSVD6eTiwWXTX144O96it0Wn3vdyfv10gHC9EtVG8cDJCLp2nKdP7dTzDTbxEaGGox8cCs5MqkCKCjiHR97OYLOX4kCclgcfR+iNfbs9AFC3mIxY8OQgsoS/gw5iOp/7IRMk1Gc5Ey5gwbdKvNfwxFVJImCOszZLpMluN9nWWELhw3lclG58o5PYlS8BB04ZJRze4QVloUv1HRrJxU6OKvhz0ilqqwdRpfUjyzVFKXjUWhNXhOBCV+KqG5MCShx2F2eFrAvCLO7tD8d7QJs/oImDvY/hLc2aTfLZGSyUjRIDTNBPzI/6iEuPxEFawZMOo4xKd2vdttF53tj4mKKgnYwGcKDmWC/LpicOlhS0btd5jt7klpeEprSPJXU90dc3EmlcGQW5hEwsoU9ioKYjC5PQfX7uTLIr4VnYECNFUwsj5BPpkDneC6wZ61dfXWD7+RUCdAbDMNl9mIVuuoASELG+oEVkcp+ji8iv4=
    file:
      - "hast-util-from-parse5.js"
      - "hast-util-from-parse5.min.js"
    on:
      tags: true
      node: '6.0'
